Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
ERROR: Could not find a version that satisfies the requirement scipy.stats (from versions: none)
ERROR: No matching distribution found for scipy.stats
ERROR: Could not find a version that satisfies the requirement scipy.interpolate (from versions: none)
ERROR: No matching distribution found for scipy.interpolate
/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.6/anaconda_3_2021.11-2021.11/1.11.0/lib/python3.9/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /home/abuild/rpmbuild/BUILD/pytorch-1.11.0/aten/src/ATen/native/TensorShape.cpp:2227.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/u/dvoss/al_pmssmwithgp/model/main.py", line 195, in <module>
    gp_pipeline.run_for_iterations(start_iter, end_iter)
  File "/u/dvoss/al_pmssmwithgp/model/main.py", line 108, in run_for_iterations
    self.model.train_model(iters=1000) 
  File "/raven/u/dvoss/al_pmssmwithgp/model/models.py", line 29, in train_model
    self.best_model, self.losses, self.losses_valid = self.model.do_train_loop(iters=iters)
  File "/raven/u/dvoss/al_pmssmwithgp/model/multitaskGP2D.py", line 79, in do_train_loop
    output = self(self.x_train)
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/models/exact_gp.py", line 257, in __call__
    res = super().__call__(*inputs, **kwargs)
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/raven/u/dvoss/al_pmssmwithgp/model/multitaskGP2D.py", line 38, in forward
    mean_x = self.mean_module(x)
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/means/mean.py", line 22, in __call__
    res = super(Mean, self).__call__(x)
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/raven/u/dvoss/al_pmssmwithgp/model/linearMean.py", line 22, in forward
    res = x.matmul(self.weights).squeeze(-1) # Making it a 2D Tensor
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)
srun: error: ravg1019: task 0: Exited with exit code 1
srun: Terminating StepId=13739888.0
