Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
Traceback (most recent call last):
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 255, in <module>
    gp_pipeline = GPModelPipeline(csv_file='M_2_fixed.csv', root_file_path='path_to_root_file.root', output_dir=output_dir)
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 36, in __init__
    self.load_data()
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 41, in load_data
    file = uproot.open(self.root_file_path)
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/reading.py", line 142, in open
    file = ReadOnlyFile(
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/reading.py", line 561, in __init__
    self._source = source_cls(file_path, **self._options)
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/source/fsspec.py", line 45, in __init__
    self._open()
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/source/fsspec.py", line 59, in _open
    self._file = self._fs.open(self._file_path)
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/spec.py", line 1303, in open
    f = self._open(
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 191, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 355, in __init__
    self._open()
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 360, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/raven/u/dvoss/al_pmssmwithgp/model/path_to_root_file.root'
srun: error: ravg1010: task 0: Exited with exit code 1
srun: Terminating StepId=12182847.0
