Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/lazy/triangular_lazy_tensor.py:136: UserWarning: torch.triangular_solve is deprecated in favor of torch.linalg.solve_triangularand will be removed in a future PyTorch release.
torch.linalg.solve_triangular has its arguments reversed and does not return a copy of one of the inputs.
X = torch.triangular_solve(B, A).solution
should be replaced with
X = torch.linalg.solve_triangular(A, B). (Triggered internally at  /home/abuild/rpmbuild/BUILD/pytorch-1.11.0/aten/src/ATen/native/BatchLinearAlgebra.cpp:1666.)
  res = torch.triangular_solve(right_tensor, self.evaluate(), upper=self.upper).solution
Traceback (most recent call last):
  File "/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 330, in <module>
    gp_pipeline.plotGP(new_x=new_points, save_path=os.path.join(args.output_dir, 'gp_plot.png'))
  File "/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 172, in plotGP
    al_df = uproot.open(self.root_file_path)["susy"].arrays(library="pd")
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/reading.py", line 142, in open
    file = ReadOnlyFile(
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/reading.py", line 561, in __init__
    self._source = source_cls(file_path, **self._options)
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/source/fsspec.py", line 45, in __init__
    self._open()
  File "/u/dvoss/.local/lib/python3.9/site-packages/uproot/source/fsspec.py", line 59, in _open
    self._file = self._fs.open(self._file_path)
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/spec.py", line 1303, in open
    f = self._open(
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 191, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 355, in __init__
    self._open()
  File "/u/dvoss/.local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 360, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/u/dvoss/al_pmssmwithgp/Run3ModelGen/source/Run3ModelGen/scans/scan_1/ntuple.0.0.root'
srun: error: ravg1023: task 0: Exited with exit code 1
srun: Terminating StepId=12300959.0
